global_costmap:
  global_frame: map
  robot_base_frame: base_footprint

  update_frequency: 5.0
  publish_frequency: 5.0
  transform_tolerance: 0.25

  static_map: true

  obstacle_range: 3.0
  raytrace_range: 3.5

  footprint:
    [[-0.105, -0.105], [-0.105, 0.105], [0.105, 0.105], [0.105, -0.105]]
  robot_radius: 0.113

  inflation_radius: 0.4
  cost_scaling_factor: 3.0

  inscribed_radius: 0.113
  circumscribed_radius: 0.113

  map_type: costmap
  observation_sources: scan
  scan:
    {
      sensor_frame: laser_link,
      data_type: LaserScan,
      topic: scan,
      marking: true,
      clearing: true,
    }
