local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint

  update_frequency: 5.0
  publish_frequency: 5.0
  transform_tolerance: 0.25

  static_map: false
  rolling_window: true
  width: 3
  height: 3
  resolution: 0.05

  obstacle_range: 3.0
  raytrace_range: 3.5

  footprint:
    [[-0.113, -0.113], [-0.113, 0.113], [0.113, 0.113], [0.113, -0.113]]
  robot_radius: 0.113

  inflation_radius: 0.75
  cost_scaling_factor: 5.0

  inscribed_radius: 0.113
  circumscribed_radius: 0.113

  map_type: costmap
  observation_sources: scan
  scan:
    {
      sensor_frame: laser_link,
      data_type: LaserScan,
      topic: scan,
      marking: true,
      clearing: true,
    }
