robot_model: agvota
robot_radius: 0.629
is_holonomic: False
actions:
  discrete:
    - name: move_forward
      linear: 0.5
      angular: 0.0
    - name: move_backward
      linear: -0.15
      angular: 0.0
    - name: turn_left
      linear: 0.15
      angular: 0.35
    - name: turn_right
      linear: 0.15
      angular: -0.35
    - name: turn_strong_left
      linear: 0.0
      angular: 0.75
    - name: turn_strong_right
      linear: 0.0
      angular: -0.75
    - name: stop
      linear: 0.0
      angular: 0.0
  continuous:
    linear_range: [-0.5, 0.5] # Maximum translational velocity in m/s
    angular_range: [-0.4, 0.4] # Maximum rotational velocity in rad/s - TODO: from, pos wrong  max_vel_theta: 0.4
laser:
  angle:
    min: -1.5707963267948966
    max: 1.5707963267948966
    increment: 0.00436332312
  num_beams: 720
  range: 30.0
  update_rate: 10
