# Training Curriculum
# this yaml serves as container of the learning curriculum for the agent
# by determining the number of static/dynamic obstacles per stage
# (will carry on training on last stage when threshhold reached)

stage_1:
  static: 0
  dynamic: 0
stage_2:
  static: 3
  dynamic: 0
stage_3:
  static: 5
  dynamic: 0
stage_4:
  static: 6
  dynamic: 1
stage_5:
  static: 7
  dynamic: 2
stage_6:
  static: 9
  dynamic: 2
stage_7:
  static: 10
  dynamic: 3
stage_8:
  static: 12
  dynamic: 4
stage_9:
  static: 15
  dynamic: 5
stage_10:
  static: 17
  dynamic: 6

# stage_1:
#   static: 0
#   dynamic: 0
# stage_2:
#   static: 6
#   dynamic: 0
# stage_3:
#   static: 10
#   dynamic: 0
# stage_4:
#   static: 12
#   dynamic: 2
# stage_5:
#   static: 14
#   dynamic: 4
# stage_6:
#   static: 18
#   dynamic: 4
# stage_7:
#   static: 20
#   dynamic: 4
# stage_8:
#   static: 24
#   dynamic: 6
# stage_9:
#   static: 30
#   dynamic: 6
# stage_10:
#   static: 34
#   dynamic: 6