# Training Curriculum
# this yaml serves as container of the learning curriculum for the agent
# by determining the number of static/dynamic obstacles per stage
# (will carry on training on last stage when threshhold reached)

stage_1:
  static: 0
  dynamic: 0
stage_2:
  static: 6
  dynamic: 0
stage_3:
  static: 10
  dynamic: 0
stage_4:
  static: 12
  dynamic: 2
stage_5:
  static: 14
  dynamic: 4
stage_6:
  static: 18
  dynamic: 4
stage_7:
  static: 20
  dynamic: 4
stage_8:
  static: 24
  dynamic: 6
stage_9:
  static: 30
  dynamic: 6
stage_10:
  static: 34
  dynamic: 6
# 1:
#   static: 0
#   dynamic: 0
# 2:
#   static: 0
#   dynamic: 4
# 3:
#   static: 0
#   dynamic: 8
# 4:
#   static: 0
#   dynamic: 12
# 5:
#   static: 0
#   dynamic: 16
# 6:
#   static: 0
#   dynamic: 20
# 7:
#   static: 0
#   dynamic: 24
# 8:
#   static: 2
#   dynamic: 28
# 9:
#   static: 2
#   dynamic: 32
# 10:
#   static: 2
#   dynamic: 40

