# Training Curriculum 
# this yaml serves as container of the learning curriculum for the agent
# by determining the number of static/dynamic obstacles per stage
# (will carry on training on last stage when threshhold reached)

stage_1:
  static: 0
  dynamic: 0
stage_2:
  static: 0
  dynamic: 4
stage_3:
  static: 1
  dynamic: 4
stage_4:
  static: 1
  dynamic: 6
stage_5:
  static: 1
  dynamic: 8
stage_6:
  static: 2
  dynamic: 7

