global_costmap:
  global_frame: map
  robot_base_frame: base_footprint

  update_frequency: 5
  publish_frequency: 5 # changed from 5 since this works better with mpc-planer
  transform_tolerance: 0.2

  static_map: true

  obstacle_range: 10.0
  raytrace_range: 15.0

  footprint: [[-0.21, -0.21], [-0.21, 0.21], [0.21, 0.21], [0.21, -0.21]]
  robot_radius: 0.267

  inflation_radius: 1.0
  cost_scaling_factor: 5.0

  inscribed_radius: 0.267
  circumscribed_radius: 0.267

  map_type: costmap
  observation_sources: scan
  scan:
    {
      sensor_frame: laser_link,
      data_type: LaserScan,
      topic: scan,
      marking: true,
      clearing: true,
    }
